import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Header from "./components/Header";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <meta charSet="utf-8" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <meta name="theme-color" content="#000000" />
                <title>Ahmed Hussein Portfolio</title>
                <meta
                    name="description"
                    content="Ahmed Hussein I am a Frontend Software Developer | React.js | Next.js"
                />
                <link rel="icon" href="/favicon.ico" />
                <meta name="og:title" content="Ahmed Hussein Portfolio" />
                <meta
                    name="og:description"
                    content="Ahmed Hussein I am a Frontend Software Developer | React.js | Next.js"
                />
                <meta name="og:image" content="/public/images/profile-image-b-w.png" />
            </head>
            <body
                className={`
                    ${geistSans.variable} ${geistMono.variable} antialiased
                    `}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                >
                    <div className=" grid grid-flow-row">
                        <div className="h-full">
                            <Header />
                        </div>
                        <main>{children}</main>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
